# -*- coding: utf-8 -*-
"""mainfyp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRRcK9CpBgKMV3gZeMIHsmurkNR4QPSV
"""

import streamlit as st
import numpy as np
import pandas as pd
import tensorflow as tf
import joblib
import librosa
import requests
import base64
import json
from datetime import datetime
import os
import tempfile
from feature_extraction import preprocess_audio_for_prediction

# Page configuration
st.set_page_config(
    page_title="EmotiTone",
    page_icon="🎭",
    layout="wide"
)

# Initialize session state
if 'results_history' not in st.session_state:
    st.session_state.results_history = []
if 'current_result' not in st.session_state:
    st.session_state.current_result = None

# Load model and scaler
@st.cache_resource
def load_model_and_scaler():
    try:
        # Load the trained model
        model = tf.keras.models.load_model('./res_model.keras')

        # Load the scaler
        scaler = joblib.load('scaler.save')

        return model, scaler
    except Exception as e:
        st.error(f"Error loading model or scaler: {e}")
        return None, None

# Emotion labels (matching your training data)
EMOTION_LABELS = ['angry', 'disgust', 'fear', 'happy', 'neutral', 'sad', 'surprise']

# Emoji mapping
EMOTION_EMOJIS = {
    'angry': '😠',
    'disgust': '🤢',
    'fear': '😨',
    'happy': '😊',
    'neutral': '😐',
    'sad': '😢',
    'surprise': '😲'
}

def generate_emoji_image(emotion, confidence, api_key):
    """Generate custom emoji using OpenAI API with improved error handling"""
    try:
        # Validate API key format
        if not api_key or not api_key.startswith('sk-'):
            st.error("Invalid API key format. OpenAI API keys should start with 'sk-'")
            return None

        emoji = EMOTION_EMOJIS.get(emotion, '😐')

        # Improved and shorter prompt to avoid token limits
        prompt = f"A simple {emotion} emoji face, circular yellow background, clear {emotion} expression"

        headers = {
            'Authorization': f'Bearer {api_key}',
            'Content-Type': 'application/json'
        }

        data = {
            'model': 'dall-e-2',
            'prompt': prompt,
            'size': '256x256',
            'n': 1
        }

        # Add better timeout and error handling
        response = requests.post('https://api.openai.com/v1/images/generations',
                               headers=headers, json=data, timeout=60)

        # Detailed error handling
        if response.status_code == 200:
            image_url = response.json()['data'][0]['url']
            return image_url
        elif response.status_code == 400:
            error_details = response.json()
            error_message = error_details.get('error', {}).get('message', 'Unknown error')
            st.error(f"API Error 400: {error_message}")
            
            # Common 400 error causes and solutions
            if 'billing' in error_message.lower():
                st.error("💳 Billing issue: Please check your OpenAI account billing status")
            elif 'quota' in error_message.lower():
                st.error("📊 Quota exceeded: You've reached your API usage limit")
            elif 'invalid' in error_message.lower():
                st.error("🔑 Invalid API key: Please check your API key")
            else:
                st.error(f"Request details: {error_details}")
            
            return None
        elif response.status_code == 401:
            st.error("🔑 Authentication failed: Invalid API key")
            return None
        elif response.status_code == 429:
            st.error("⏰ Rate limit exceeded: Please wait and try again")
            return None
        else:
            st.error(f"API Error {response.status_code}: {response.text}")
            return None

    except requests.exceptions.Timeout:
        st.error("⏰ Request timeout: The API call took too long")
        return None
    except requests.exceptions.RequestException as e:
        st.error(f"🌐 Network error: {e}")
        return None
    except Exception as e:
        st.error(f"🔧 Unexpected error generating emoji: {e}")
        return None

def predict_emotion(audio_file, model, scaler):
    """Predict emotion from audio file"""
    try:
        # Save uploaded file temporarily
        with tempfile.NamedTemporaryFile(delete=False, suffix='.wav') as tmp_file:
            tmp_file.write(audio_file.read())
            tmp_file_path = tmp_file.name

        # Preprocess audio
        features = preprocess_audio_for_prediction(tmp_file_path)

        # Clean up temporary file
        os.unlink(tmp_file_path)

        # Check if features are valid
        if features is None or np.all(features == 0):
            st.error("Could not extract features from audio file")
            return None, None, None

        # Scale features
        features_scaled = scaler.transform(features)

        # Reshape for model input (add dimension for 1D CNN)
        features_reshaped = np.expand_dims(features_scaled, axis=2)

        # Make prediction
        prediction = model.predict(features_reshaped, verbose=0)

        # Get predicted emotion and confidence
        predicted_class = np.argmax(prediction[0])
        confidence = np.max(prediction[0]) * 100
        predicted_emotion = EMOTION_LABELS[predicted_class]

        # Get all probabilities
        all_probabilities = {
            EMOTION_LABELS[i]: float(prediction[0][i])
            for i in range(len(EMOTION_LABELS))
        }

        return predicted_emotion, confidence, all_probabilities

    except Exception as e:
        st.error(f"Error predicting emotion: {e}")
        return None, None, None

def main():
    st.title("🎭 EmotiTone : Speech Emotion Recognition")
    st.markdown("Upload an audio file to detect emotion and generate a custom emoji picture")

    # Load model and scaler
    model, scaler = load_model_and_scaler()

    if model is None or scaler is None:
        st.error("Failed to load model or scaler. Please check your files.")
        return

    # Sidebar
    with st.sidebar:
        st.header("About")
        st.markdown("""
        This app recognizes emotions from speech using a convolutional neural
        network and generates custom emoji pictures.

        **Supported emotions:**
        - Happy 😊
        - Sad 😢
        - Angry 😠
        - Neutral 😐
        - Fear 😨
        - Disgust 🤢
        - Surprise 😲
        """)

        st.header("Instructions")
        st.markdown("""
        1. Upload a WAV audio file containing speech
        2. The app will process your audio and predict the emotion
        3. A custom emoji picture will be generated to represent the emotion
        4. Results will be saved for the session
        """)

        st.header("API Key Configuration")
        st.markdown("⚠️ **Important:** You need an OpenAI API key with billing enabled")
        api_key = st.text_input("Enter OpenAI API Key (for emoji generation)",
                               type="password", key="api_key",
                               help="Your API key should start with 'sk-' and have billing enabled")
        
        if api_key:
            if api_key.startswith('sk-'):
                st.success("✅ API Key format looks correct!")
            else:
                st.warning("⚠️ API Key should start with 'sk-'")

        # Add API status check button
        if api_key and st.button("🔍 Test API Key"):
            with st.spinner("Testing API key..."):
                test_response = requests.get(
                    'https://api.openai.com/v1/models',
                    headers={'Authorization': f'Bearer {api_key}'},
                    timeout=10
                )
                if test_response.status_code == 200:
                    st.success("✅ API Key is valid and working!")
                else:
                    st.error(f"❌ API Key test failed: {test_response.status_code}")

    # Main content
    col1, col2 = st.columns([1, 1])

    with col1:
        st.header("Upload Audio File")

        uploaded_file = st.file_uploader(
            "Choose an audio file",
            type=['wav', 'mp3'],
            help="Upload a WAV or MP3 file containing speech (max 200MB)"
        )

        if uploaded_file is not None:
            # Display file info
            st.info(f"File: {uploaded_file.name} ({uploaded_file.size/1024:.1f} KB)")

            # Play audio
            st.audio(uploaded_file, format='audio/wav')

            # Predict emotion
            if st.button("🔍 Analyze Emotion", type="primary"):
                with st.spinner("Analyzing emotion..."):
                    emotion, confidence, probabilities = predict_emotion(
                        uploaded_file, model, scaler
                    )

                    if emotion is not None:
                        # Store result
                        result = {
                            'filename': uploaded_file.name,
                            'emotion': emotion,
                            'confidence': confidence,
                            'probabilities': probabilities,
                            'timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                            'emoji_url': None
                        }

                        # Generate emoji if API key is provided
                        if api_key and api_key.strip():
                            with st.spinner("Generating custom emoji..."):
                                emoji_url = generate_emoji_image(emotion, confidence, api_key)
                                result['emoji_url'] = emoji_url
                        else:
                            st.info("💡 Enter an OpenAI API key to generate custom emoji images")

                        # Save to session state
                        st.session_state.current_result = result
                        st.session_state.results_history.append(result)

                        st.success(f"✅ Analysis complete!")

    with col2:
        st.header("Results")

        # Display current result
        if st.session_state.current_result:
            result = st.session_state.current_result

            # Main result display
            st.subheader(f"🎭 Detected Emotion: **{result['emotion'].title()}**")
            st.metric("Confidence", f"{result['confidence']:.2f}%")

            # Show emoji
            emoji = EMOTION_EMOJIS.get(result['emotion'], '😐')
            st.markdown(f"### {emoji}")

            # Show custom generated emoji if available
            if result['emoji_url']:
                st.image(result['emoji_url'], caption="Custom Generated Emoji", width=200)

            # Show all probabilities
            st.subheader("All Probabilities:")
            prob_df = pd.DataFrame(
                [(emotion, f"{prob*100:.2f}%") for emotion, prob in result['probabilities'].items()],
                columns=['Emotion', 'Probability']
            ).sort_values('Probability', ascending=False)

            st.dataframe(prob_df, use_container_width=True)

        else:
            st.info("Upload an audio file and click 'Analyze Emotion' to see results here.")

    # Results history
    if st.session_state.results_history:
        st.header("📊 Previous Analysis Results")

        # Create expandable sections for each result
        for i, result in enumerate(reversed(st.session_state.results_history)):
            with st.expander(f"Result #{len(st.session_state.results_history)-i}: {result['filename']} - {result['emotion'].title()} ({result['timestamp']})"):
                col1, col2, col3 = st.columns([1, 1, 1])

                with col1:
                    st.write(f"**Emotion:** {result['emotion'].title()}")
                    st.write(f"**Confidence:** {result['confidence']:.2f}%")

                with col2:
                    emoji = EMOTION_EMOJIS.get(result['emotion'], '😐')
                    st.markdown(f"### {emoji}")

                with col3:
                    if result['emoji_url']:
                        st.image(result['emoji_url'], width=100)

                # Show probabilities
                st.subheader("All Probabilities:")
                for emotion, prob in sorted(result['probabilities'].items(),
                                          key=lambda x: x[1], reverse=True):
                    st.write(f"- **{emotion.title()}:** {prob*100:.2f}%")

        # Clear history button
        if st.button("🗑️ Clear History"):
            st.session_state.results_history = []
            st.session_state.current_result = None
            st.rerun()

if __name__ == "__main__":
    main()