# -*- coding: utf-8 -*-
"""feature_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aU49N7QNDTaWKPjAo0vGxVOKSTHB0aau
"""

import librosa
import numpy as np
import pandas as pd

def add_noise(data, random=False, rate=0.035, threshold=0.075):
    """Add noise to audio data"""
    if random:
        rate = np.random.random() * threshold
    noise = rate * np.random.uniform() * np.amax(data)
    augmented_data = data + noise * np.random.normal(size=data.shape[0])
    return augmented_data

def shifting(data, rate=1000):
    """Shift audio data"""
    augmented_data = int(np.random.uniform(low=-5, high=5) * rate)
    augmented_data = np.roll(data, augmented_data)
    return augmented_data

def pitching(data, sr, pitch_factor=0.7, random=False):
    """Change pitch of audio data"""
    if random:
        pitch_factor = np.random.random() * pitch_factor
    return librosa.effects.pitch_shift(y=data, sr=sr, n_steps=pitch_factor)

def stretching(data, rate=0.8):
    """Stretch audio data"""
    return librosa.effects.time_stretch(y=data, rate=rate)

def extract_features(data, sr, frame_length=2048, hop_length=512):
    """Extract exactly 52 features to match your trained model"""
    result = np.array([])

    try:
        # MFCC features (13 coefficients * 4 statistics = 52 features)
        mfcc_feat = librosa.feature.mfcc(y=data, sr=sr, n_mfcc=13,
                                       hop_length=hop_length, n_fft=frame_length)

        # Calculate statistics for each coefficient
        for i in range(mfcc_feat.shape[0]):  # 13 coefficients
            result = np.hstack((result,
                               np.mean(mfcc_feat[i]),    # Mean
                               np.std(mfcc_feat[i]),     # Standard deviation
                               np.min(mfcc_feat[i]),     # Minimum
                               np.max(mfcc_feat[i])))    # Maximum

        # Ensure we have exactly 52 features
        if len(result) != 52:
            print(f"Warning: Expected 52 features, got {len(result)}")
            # Pad with zeros if too few, truncate if too many
            if len(result) < 52:
                result = np.pad(result, (0, 52 - len(result)), 'constant')
            else:
                result = result[:52]

    except Exception as e:
        print(f"Error extracting features: {e}")
        # Return zero array if extraction fails
        result = np.zeros(52)

    return result

def get_features(path):
    """Get features from audio file with data augmentation"""
    try:
        # Load audio file
        data, sr = librosa.load(path, duration=3, offset=0.5, res_type='kaiser_fast')

        # Original features
        features = []

        # 1. Original audio
        res1 = extract_features(data, sr)
        features.append(res1)

        # 2. Add noise
        try:
            noise_data = add_noise(data, random=True)
            res2 = extract_features(noise_data, sr)
            features.append(res2)
        except:
            features.append(res1)  # Use original if noise fails

        # 3. Pitch shift
        try:
            pitch_data = pitching(data, sr, random=True)
            res3 = extract_features(pitch_data, sr)
            features.append(res3)
        except:
            features.append(res1)  # Use original if pitch fails

        # 4. Time stretch
        try:
            stretch_data = stretching(data)
            res4 = extract_features(stretch_data, sr)
            features.append(res4)
        except:
            features.append(res1)  # Use original if stretch fails

        # 5. Shift
        try:
            shift_data = shifting(data)
            res5 = extract_features(shift_data, sr)
            features.append(res5)
        except:
            features.append(res1)  # Use original if shift fails

        return features

    except Exception as e:
        print(f"Error processing file {path}: {e}")
        # Return array of zeros if file processing fails
        return [np.zeros(52) for _ in range(5)]

def preprocess_audio_for_prediction(file_path):
    """Preprocess single audio file for prediction"""
    try:
        # Load audio
        data, sr = librosa.load(file_path, duration=3, offset=0.5, res_type='kaiser_fast')

        # Extract features (no augmentation for prediction)
        features = extract_features(data, sr)

        # Ensure we have exactly 52 features
        if len(features) != 52:
            print(f"Feature mismatch: got {len(features)}, expected 52")
            if len(features) < 52:
                features = np.pad(features, (0, 52 - len(features)), 'constant')
            else:
                features = features[:52]

        return features.reshape(1, -1)  # Reshape for single prediction

    except Exception as e:
        print(f"Error preprocessing audio: {e}")
        return np.zeros(52).reshape(1, -1)